### ISSUE TITLE
Defaulting semver should be patch

### ISSUE THREAD

**Issue by danneleaf** [janderssonse/janderscripts#19]
After consulting with the maintainer, we propose to alter what version this script defaults to when creating a new tag. We suggest replacing the current default value which increases the minor version with an increase to the patch version instead eg 0.0.0 to 0.1.0 will instead become 0.0.0 to 0.0.1.
Fixing this would lead to a more expected behavior according to us, for more info about semver, see [semver 2.0.0](https://semver.org)

**Comment by janderssonse** [comment]
Fixed by https://github.com/janderssonse/janderscripts/commit/e6b1509e4e55458bf20eba7fb6402383a2ca1a2e.

Closing, thank for the patch! 👍
